### ISSUE TITLE
Failed to use stylelint-module

### ISSUE THREAD

**Issue by clamarque** [nuxt-community/stylelint-module#23]
Hi 👋  ! I have a problem when i use @nuxtjs/stylelint-module (v3.1.0) . I respect the README description and i get this error: Your Nuxt.js app could not be shown even though the webpack build appears to have finished. In the terminal, The client party didn't compile. If I try to remove the module from buildModules, the client reach compiled. I use nuxtJS V2.10.2. Thanks for help.

**Comment by 1001v** [comment]
I can confirm this. I use nuxt 2.10.2 as well.

**Comment by ricardogobbosouza** [comment]
Hi @clamarque thanks for reporting
This is because there is no configuration file `stylelint.config.js`
This will be fixed soon https://github.com/webpack-contrib/stylelint-webpack-plugin/issues/197

**Comment by ricardogobbosouza** [comment]
Resolved on v3.1.1

**Comment by eliyas5044** [comment]
@ricardogobbosouza sorry to comment in closed issue, but this issue still exist.
`
"nuxt": "^2.11.0"
"@nuxtjs/stylelint-module": "^3.2.1"
`
> No rules found within configuration. Have you provided a "rules" property?

**Comment by ricardogobbosouza** [comment]
@eliyas5044 
Your `stylelint.config.js` file must have a rule, but that doesn't make the module fail.
I can't reproduce if I can provide a repository

**Comment by eliyas5044** [comment]
@ricardogobbosouza My point is you just create a new `nuxt` project with `npx create-nuxt-app my-app` and after finish, you tried to run with `npm run dev` and it failed due to this *stylelint* problem, this is not expected i guess. My opinion is, if we must need to add some rules in `stylelint.config.js` when we are creating app, this module should add some default configs in this file.

pardon me if i am wrong :(

**Comment by ricardogobbosouza** [comment]
@eliyas5044 this is expected because of this file https://github.com/nuxt/create-nuxt-app/blob/master/template/_stylelint.config.js

**Comment by ricardogobbosouza** [comment]
It is not a problem with this module, but because the rules are blank
We can think of adding some basic rule by default
